# Generated by Django 3.1.5 on 2021-01-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(max_length=100),
        ),
    ]
